# Generated by Django 4.1.4 on 2023-01-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_Articulo',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
