# Generated by Django 4.1.5 on 2023-01-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0002_tb_articulo_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('telefono', models.IntegerField(primary_key=True, serialize=False, verbose_name='telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='correo')),
                ('mensaje', models.CharField(max_length=200, verbose_name='mensaje')),
            ],
        ),
        migrations.DeleteModel(
            name='Tb_Articulo',
        ),
    ]
